{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "31599e74",
   "metadata": {},
   "outputs": [],
   "source": [
    "import yaltai"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "480e4e11",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/Theo/dev/yolov5\n"
     ]
    }
   ],
   "source": [
    "cd ~/dev/yolov5/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5774d5fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-03-03 10:17:52.868423: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "TensorFlow version 2.11.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.10.0 is the most recent version that has been tested.\n",
      "Loading ANN /usr/local/anaconda3/lib/python3.9/site-packages/kraken/blla.mlmodel\t\u001b[0mSegmenting\t\u001b[0mDownloading: \"https://github.com/ultralytics/yolov5/zipball/v6.2\" to /Users/Theo/.cache/torch/hub/v6.2.zip\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/125912_archives_FRAD075RM_D4R1_2032_0195_D.jpg\n",
      "TopologyException: side location conflict at 1008.9808612440191 501.60765550239233. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:18:34]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=728712;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=99005;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 997.36363636363637 501.5090909090909. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=276905;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=360808;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 757.78205128205127 1622.6794871794871. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=38067;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=994416;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 792.68037974683546 970. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:18:35]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=729066;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=335876;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 961.75 976.25. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=179978;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=811660;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 191.59036144578315 1448.8685651697699. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:18:37]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=981229;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=882346;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 799.04878048780483 971.1219512195122. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=725405;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=896563;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:18:44]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=214353;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=981443;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m125912_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_2032_0195_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/125912_archives_FRAD075RM_D4R1_2032_0195_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/377217_archives_FRAD075RM_D4R1_1992_0681_D.jpg\n",
      "TopologyException: side location conflict at 930.79999999999995 1490.8. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:00]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=534342;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=207958;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TopologyException: side location conflict at 859.14617618586635 1022.0348499515973. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:01]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=459011;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=26193;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1037.6666666666667 1009. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=241429;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=601809;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1062.4497936726273 1633.2682255845941. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=494170;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=739236;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 921.16666666666663 1489. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:02]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=790387;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=649593;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:19:10]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=596180;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=169845;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m377217_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1992_0681_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/377217_archives_FRAD075RM_D4R1_1992_0681_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/118503_archives_FRAD075RM_D4R1_1579_0647_D.jpg\n",
      "TopologyException: side location conflict at 792.57894736842104 1616.1052631578948. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:25]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=311873;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=286753;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 891.57692307692309 140.76923076923077. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=270485;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=330200;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 238.9375 1598. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=777268;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=681903;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 849.60000000000002 995.39999999999998. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:26]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=706273;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=613321;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:19:33]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=427439;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=642770;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m118503_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1579_0647_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/118503_archives_FRAD075RM_D4R1_1579_0647_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/211530_archives_FRAD075RM_D4R1_1407_0063_D.jpg\n",
      "TopologyException: side location conflict at 758.17073170731703 1591. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:49]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=794320;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=836767;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 913.8603859250851 1595.5936435868332. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=619185;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=546897;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 781.14285714285711 980. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=828803;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=686016;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 961 979.4545454545455. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:50]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=170479;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=544470;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 798.71428571428567 981.71428571428567. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:19:51]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=845538;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=73992;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:20:00]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=617402;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=166611;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m211530_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1407_0063_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/211530_archives_FRAD075RM_D4R1_1407_0063_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/749504_archives_FRAD075RM_D4R1_1223_0283_D.jpg\n",
      "TopologyException: side location conflict at 932.97526501766788 1379.4098939929329. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:14]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=937126;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=409762;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=738277;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=773691;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         all the input arrays must have  \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         same number of dimensions, but  \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         the array at index \u001b[1;36m0\u001b[0m has \u001b[1;36m1\u001b[0m      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[1;35mdimension\u001b[0m\u001b[1m(\u001b[0ms\u001b[1m)\u001b[0m and the array at   \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         index \u001b[1;36m1\u001b[0m has \u001b[1;36m2\u001b[0m \u001b[1;35mdimension\u001b[0m\u001b[1m(\u001b[0ms\u001b[1m)\u001b[0m      \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)\n",
      "TopologyException: side location conflict at 573.91474245115455 442.37122557726468. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:21]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=925970;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=507546;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:20:26]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=218958;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=904824;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m749504_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1223_0283_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/749504_archives_FRAD075RM_D4R1_1223_0283_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/364183_archives_FRAD075RM_D4R1_1251_0781_D.jpg\n",
      "TopologyException: side location conflict at 683.87580725285648 932.88375558867358. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:41]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=681529;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=945066;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 819.84881043745202 567.81504221028399. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=354567;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=905510;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 926.85714285714289 1323.4285714285713. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:42]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=59825;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=989951;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 888 1359.5. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:43]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=497134;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=458738;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 397.06278538812785 408.80251141552509. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:45]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=484344;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=605647;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 455.16216216216219 409.91891891891891. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:46]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=148916;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=827289;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 867.44262295081967 1544. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:20:47]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=455132;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=362585;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:20:51]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=166484;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=70409;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m364183_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1251_0781_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/364183_archives_FRAD075RM_D4R1_1251_0781_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/704913_archives_FRAD075RM_D4R1_0701_0424_D.jpg\n",
      "TopologyException: side location conflict at 924.5 1369. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:21:15]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=494163;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=65675;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 889 1372. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=42192;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=416678;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TopologyException: side location conflict at 930.91666666666663 1368. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=366487;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=875991;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:21:28]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=338543;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=145201;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m704913_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_0701_0424_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/704913_archives_FRAD075RM_D4R1_0701_0424_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/385353_archives_FRAD075RM_D4R1_0736_0514_D.jpg\n",
      "TopologyException: side location conflict at 475.14285714285717 273.57142857142856. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:21:44]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=989316;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=605845;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 887.28767123287673 1343.5068493150684. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=172405;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=885262;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 351.00700466977986 667.77384923282193. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:21:45]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=509371;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=826210;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 923.43478260869563 1345.3478260869565. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=911740;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=860173;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 875.05427408412481 170.0461329715061. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=484360;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=921617;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 577.37931034482756 667.62068965517244. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=783549;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=30262;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 759.75 1563.75. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=588557;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=814664;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 761.60000000000002 1566.2. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:21:46]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=100488;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=355543;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TopologyException: side location conflict at 853 1574.5762081784387. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:21:48]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=381113;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=584127;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:21:55]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=410125;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=879538;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m385353_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_0736_0514_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/385353_archives_FRAD075RM_D4R1_0736_0514_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/649973_archives_FRAD075RM_D4R1_1185_0203_D.jpg\n",
      "TopologyException: side location conflict at 1008.5 976. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:10]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=472630;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=910851;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 894.42857142857144 1329.4285714285713. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:11]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=214661;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=855911;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 921.94117647058829 1328.4705882352941. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=669324;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=621672;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 511 501. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:12]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=146519;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=983444;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 524.01960784313724 634.98039215686276. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=317037;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=611806;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 433.07692307692309 636.92307692307691. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:13]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=263528;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=154080;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 853.16216216216219 1558. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:15]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=433136;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=52571;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:22:20]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=341226;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=210492;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m649973_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1185_0203_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/649973_archives_FRAD075RM_D4R1_1185_0203_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/214660_archives_FRAD075RM_D4R1_1316_0195_D.jpg\n",
      "TopologyException: side location conflict at 1055.8626446038952 971.97349538731874. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:36]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=599896;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=559697;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 825.33333333333337 111.93333333333334. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=443632;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=479618;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 928.75 1324. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:37]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=524572;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=900271;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 959.87378640776694 1371.6893203883494. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=15986;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=312658;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 582.45434298440978 609.79064587973278. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=240805;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=713215;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 470.85719407265776 609.76159177820273. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:22:38]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=675393;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=759913;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:22:48]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=646628;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=612;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m214660_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1316_0195_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/214660_archives_FRAD075RM_D4R1_1316_0195_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/338542_archives_FRAD075RM_D4R1_1141_0599_D.jpg\n",
      "TopologyException: side location conflict at 1039.9043478260869 990.77391304347827. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:04]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=66089;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=83748;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1023.1512455516014 795.017793594306. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=51348;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=884018;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1036.1935483870968 992.73900293255133. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=13174;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=279111;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TopologyException: side location conflict at 869.33333333333337 1343.8333333333333. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:05]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=341778;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=673090;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 914 1384. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=690581;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=613963;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 564.19955654102 652.50332594235033. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=886515;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=150142;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 384.84463061690786 651.66945925361767. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:06]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=924663;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=496527;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "\u001b[2;36m[03/03/23 10:23:14]\u001b[0m\u001b[2;36m \u001b[0m\u001b[1;31mERROR   \u001b[0m Failed processing              \u001b]8;id=524394;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py\u001b\\\u001b[2mkraken_yaltai.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=257401;file:///usr/local/anaconda3/lib/python3.9/site-packages/yaltai/kraken_yaltai.py#201\u001b\\\u001b[2m201\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35m/Users/Theo/Desktop/14-18/tran\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[35mscription/total/\u001b[0m\u001b[95m338542_archive\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95ms_FRAD075RM_D4R1_1141_0599_D.j\u001b[0m \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[95mpg\u001b[0m: expected token \u001b[32m'end of \u001b[0m    \u001b[2m                    \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         \u001b[32mstatement block'\u001b[0m, got \u001b[32m'+'\u001b[0m      \u001b[2m                    \u001b[0m\n",
      "Failed processing /Users/Theo/Desktop/14-18/transcription/total/338542_archives_FRAD075RM_D4R1_1141_0599_D.jpg: expected token 'end of statement block', got '+'\n",
      "Segmenting\t\u001b[0mUsing cache found in /Users/Theo/.cache/torch/hub/ultralytics_yolov5_v6.2\n",
      "YOLOv5 ðŸš€ 2023-3-3 Python-3.9.13 torch-1.13.1 CPU\n",
      "\n",
      "Fusing layers... \n",
      "Model summary: 322 layers, 86233975 parameters, 0 gradients, 203.9 GFLOPs\n",
      "Adding AutoShape... \n",
      "Segmenting /Users/Theo/Desktop/14-18/transcription/total/474762_archives_FRAD075RM_D4R1_2069_0947_D.jpg\n",
      "TopologyException: side location conflict at 1303.7293114339861 1671.0328490208465. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:39]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=596236;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=465781;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 429.22018348623851 1036.211009174312. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:41]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=789931;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=854909;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1349.2 1115.8. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:42]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=934965;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=100361;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1556.0736364885286 1666.7575216375876. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=912151;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=916306;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1436.7050298380223 1532.7664109121911. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:43]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=505323;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=317559;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TopologyException: side location conflict at 1409.9661016949153 1525.3898305084747. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=718131;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=750532;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1498.5 1037.5. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m                   \u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=689392;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=177571;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "TopologyException: side location conflict at 1500 1037. This can occur if the input geometry is invalid.\n",
      "\u001b[2;36m[03/03/23 10:23:45]\u001b[0m\u001b[2;36m \u001b[0m\u001b[31mWARNING \u001b[0m Polygonizer failed on line \u001b[1;36m0\u001b[0m:   \u001b]8;id=430414;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py\u001b\\\u001b[2msegmentation.py\u001b[0m\u001b]8;;\u001b\\\u001b[2m:\u001b[0m\u001b]8;id=585642;file:///usr/local/anaconda3/lib/python3.9/site-packages/kraken/lib/segmentation.py#735\u001b\\\u001b[2m735\u001b[0m\u001b]8;;\u001b\\\n",
      "\u001b[2;36m                    \u001b[0m         No Shapely geometry can be      \u001b[2m                   \u001b[0m\n",
      "\u001b[2;36m                    \u001b[0m         created from null value         \u001b[2m                   \u001b[0m\n",
      "Polygonizer failed on line 0: No Shapely geometry can be created from null value\n",
      "^C\n",
      "\n",
      "Aborted!\n"
     ]
    }
   ],
   "source": [
    "! yaltai kraken --device cpu -I \"/Users/Theo/Desktop/14-18/transcription/total_test/*.jpg\" --suffix \".xml\" segment --yolo runs/train/exp8/weights/best.pt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1af4b662",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "absl-py==1.3.0\r\n",
      "aiohttp==3.8.4\r\n",
      "aiosignal==1.3.1\r\n",
      "alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work\r\n",
      "anaconda-client==1.11.0\r\n",
      "anaconda-navigator==2.3.1\r\n",
      "anaconda-project @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_52iciqycjz/croots/recipe/anaconda-project_1660339902500/work\r\n",
      "antlr4-python3-runtime==4.9.3\r\n",
      "anyio @ file:///opt/concourse/worker/volumes/live/485b0f52-1188-482a-6285-65a36c8fa8a6/volume/anyio_1644481714856/work/dist\r\n",
      "appdirs==1.4.4\r\n",
      "applaunchservices @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_96v71vcny2/croots/recipe/applaunchservices_1661854626389/work\r\n",
      "appnope @ file:///opt/concourse/worker/volumes/live/6ca6f098-d773-4461-5c91-a24a17435bda/volume/appnope_1606859448531/work\r\n",
      "appscript @ file:///opt/concourse/worker/volumes/live/00049ed6-6263-4a6e-72b9-9d990f6e2f07/volume/appscript_1611427000595/work\r\n",
      "argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work\r\n",
      "argon2-cffi-bindings @ file:///opt/concourse/worker/volumes/live/42cf1b28-e71f-45ed-47b2-50f828088636/volume/argon2-cffi-bindings_1644569709119/work\r\n",
      "arrow @ file:///opt/conda/conda-bld/arrow_1649166651673/work\r\n",
      "astroid @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9fsa1cbbec/croots/recipe/astroid_1659023133872/work\r\n",
      "astropy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0a17b8e9-1fad-48c5-91fb-b4dded6b289flor4xw5u/croots/recipe/astropy_1657786108950/work\r\n",
      "astunparse==1.6.3\r\n",
      "async-timeout==4.0.2\r\n",
      "atomicwrites==1.4.0\r\n",
      "attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work\r\n",
      "Automat @ file:///tmp/build/80754af9/automat_1600298431173/work\r\n",
      "autopep8 @ file:///opt/conda/conda-bld/autopep8_1650463822033/work\r\n",
      "Babel @ file:///tmp/build/80754af9/babel_1620871417480/work\r\n",
      "backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work\r\n",
      "backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work\r\n",
      "backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work\r\n",
      "backports.weakref==1.0.post1\r\n",
      "bcrypt @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b550nfy8c3/croots/recipe/bcrypt_1659554333520/work\r\n",
      "beautifulsoup4 @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_croot-cdiouih5/beautifulsoup4_1650462164803/work\r\n",
      "binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work\r\n",
      "bitarray @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_99410e05-b235-43fd-a31c-8dd2d61509a4vi1pzh3o/croots/recipe/bitarray_1657739652745/work\r\n",
      "bkcharts==0.2\r\n",
      "black @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d0nhgmyc3l/croots/recipe/black_1660237813406/work\r\n",
      "bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work\r\n",
      "blis==0.7.9\r\n",
      "bokeh @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4689ce87-cfaa-4ded-b2ca-a10b180c8012082opaxd/croots/recipe/bokeh_1658136657265/work\r\n",
      "boto3 @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7466793a-6ce0-4cc8-b633-fb7f60016ad6lnn62tpt/croots/recipe/boto3_1657820107850/work\r\n",
      "botocore @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_05d2e560-e0a7-4311-8a55-e8216b7418d7ho9lnfo9/croots/recipe/botocore_1657739494502/work\r\n",
      "Bottleneck @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_29949159-f86f-474b-bc1f-aaa1e0e222b4ofusifik/croots/recipe/bottleneck_1657175564045/work\r\n",
      "branca==0.6.0\r\n",
      "brotlipy==0.7.0\r\n",
      "cachetools==5.2.0\r\n",
      "catalogue==1.0.2\r\n",
      "certifi==2022.12.7\r\n",
      "cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_62rp5d8fd4/croots/recipe/cffi_1659598655556/work\r\n",
      "chardet @ file:///opt/concourse/worker/volumes/live/7e1102c4-8702-40f2-63d6-f260ce5f85e4/volume/chardet_1607706831384/work\r\n",
      "charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work\r\n",
      "click==8.1.3\r\n",
      "click-plugins==1.1.1\r\n",
      "cligj==0.7.2\r\n",
      "cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work\r\n",
      "clyent==1.2.2\r\n",
      "colorama @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b8ecd5af-5e60-48b8-80ac-92164ecb9b9bxkf0tkfp/croots/recipe/colorama_1657009097162/work\r\n",
      "colorcet @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_8a83eeb2-7dbf-4e61-829c-ba42fc3fd6f523ifr0ew/croots/recipe/colorcet_1651851028480/work\r\n",
      "conda==22.11.1\r\n",
      "conda-build==3.22.0\r\n",
      "conda-content-trust @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0afea0f9-bbf5-446c-8d60-8151cc05b029p0nco1nn/croots/recipe/conda-content-trust_1658126375910/work\r\n",
      "conda-pack @ file:///tmp/build/80754af9/conda-pack_1611163042455/work\r\n",
      "conda-package-handling @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4aholt4czv/croots/recipe/conda-package-handling_1663598478352/work\r\n",
      "conda-repo-cli==1.0.20\r\n",
      "conda-token @ file:///Users/paulyim/miniconda3/envs/c3i/conda-bld/conda-token_1662660369760/work\r\n",
      "conda-verify==3.4.2\r\n",
      "confection==0.0.3\r\n",
      "constantly==15.1.0\r\n",
      "cookiecutter @ file:///opt/conda/conda-bld/cookiecutter_1649151442564/work\r\n",
      "coremltools==6.2\r\n",
      "cryptography @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b470f7cb-c8f1-42c9-b84f-23789ea77e7c9difcqh4/croots/recipe/cryptography_1652101134392/work\r\n",
      "cssselect==1.1.0\r\n",
      "cycler==0.10.0\r\n",
      "cymem==2.0.7\r\n",
      "Cython @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_2bxfxrakym/croots/recipe/cython_1663692778284/work\r\n",
      "cytoolz==0.11.0\r\n",
      "daal4py==2021.6.0\r\n",
      "dask @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_625ab4ad-a7aa-46be-859b-eb7a32fc37bc46adm9wx/croots/recipe/dask-core_1658513219136/work\r\n",
      "datashader @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_543d57cxkz/croots/recipe/datashader_1659349048901/work\r\n",
      "datashape==0.5.4\r\n",
      "debugpy @ file:///opt/concourse/worker/volumes/live/fb0af3c0-b0a4-42c5-46e7-6ce9c84da602/volume/debugpy_1637091827531/work\r\n",
      "decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work\r\n",
      "defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work\r\n",
      "detectron2 @ git+https://github.com/facebookresearch/detectron2.git@4aca4bdaa9ad48b8e91d7520e0d0815bb8ca0fb1\r\n",
      "diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work\r\n",
      "dill @ file:///tmp/build/80754af9/dill_1623919422540/work\r\n",
      "display-xml==0.1.0\r\n",
      "distributed @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_ca26b14a-a121-44b5-82b0-dbb6ccf35309a1h39fbg/croots/recipe/distributed_1658520748547/work\r\n",
      "docutils @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_10cfb287-0327-45ef-a38e-53dffd30cef1nwpvy20e/croots/recipe/docutils_1657175439973/work\r\n",
      "emoji==2.2.0\r\n",
      "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz\r\n",
      "entrypoints @ file:///opt/concourse/worker/volumes/live/78b2c4ae-da17-4aa7-7fdc-138f840abf07/volume/entrypoints_1649926486598/work\r\n",
      "et-xmlfile==1.1.0\r\n",
      "fast-deskew==1.0\r\n",
      "fastjsonschema @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b5c1gee32t/croots/recipe/python-fastjsonschema_1661368622875/work\r\n",
      "filelock @ file:///opt/conda/conda-bld/filelock_1647002191454/work\r\n",
      "Fiona==1.8.22\r\n",
      "flake8 @ file:///opt/conda/conda-bld/flake8_1648129545443/work\r\n",
      "Flask @ file:///home/ktietz/src/ci/flask_1611932660458/work\r\n",
      "flatbuffers==22.12.6\r\n",
      "folium==0.13.0\r\n",
      "fonttools==4.25.0\r\n",
      "fr-core-news-md @ https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-2.3.0/fr_core_news_md-2.3.0.tar.gz\r\n",
      "fr-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.3.0/fr_core_news_sm-2.3.0.tar.gz\r\n",
      "frozenlist==1.3.3\r\n",
      "fsspec @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_a6evhlwhh2/croots/recipe/fsspec_1659972205208/work\r\n",
      "future @ file:///opt/concourse/worker/volumes/live/f456638c-86a7-4060-7f5f-d499a051219b/volume/future_1607571337593/work\r\n",
      "fuzzywuzzy==0.18.0\r\n",
      "fvcore==0.1.3.post20210317\r\n",
      "gast==0.4.0\r\n",
      "gensim==3.8.3\r\n",
      "geojson==2.5.0\r\n",
      "geopandas==0.12.1\r\n",
      "gitdb==4.0.10\r\n",
      "GitPython==3.1.31\r\n",
      "glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work\r\n",
      "gmpy2 @ file:///opt/concourse/worker/volumes/live/3b0f84f9-2a9c-48c9-6340-601e345ea292/volume/gmpy2_1645455548178/work\r\n",
      "google-auth==2.15.0\r\n",
      "google-auth-oauthlib==0.4.6\r\n",
      "google-pasta==0.2.0\r\n",
      "gpxpy==1.5.0\r\n",
      "greenlet @ file:///opt/concourse/worker/volumes/live/b27b4e9e-4697-4d57-403b-f82d36a391ca/volume/greenlet_1628888146890/work\r\n",
      "grpcio==1.51.1\r\n",
      "h5py @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7fnj4n39p5/croots/recipe/h5py_1659091379933/work\r\n",
      "HeapDict @ file:///Users/ktietz/demo/mc3/conda-bld/heapdict_1630598515714/work\r\n",
      "holoviews @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_a4562da9-f241-4c26-af69-a183348d22b8tzntcgqc/croots/recipe/holoviews_1658171511476/work\r\n",
      "huggingface-hub==0.11.1\r\n",
      "hvplot @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_20gh5adwn_/croots/recipe/hvplot_1659026499732/work\r\n",
      "hyperlink @ file:///tmp/build/80754af9/hyperlink_1610130746837/work\r\n",
      "idna==2.10\r\n",
      "imagecodecs @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_bahrk9gfto/croots/recipe/imagecodecs_1664561989889/work\r\n",
      "imageio @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5460df32-49d6-4565-9afb-ddc7de276101dvh8sph9/croots/recipe/imageio_1658785049436/work\r\n",
      "imagesize @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4a6ed1be-fe30-4d6a-91d4-f867600caa0be5_dxzvt/croots/recipe/imagesize_1657179500955/work\r\n",
      "importlib-metadata @ file:///opt/concourse/worker/volumes/live/04344671-a59e-4800-6391-124f9c0e5484/volume/importlib-metadata_1648562417587/work\r\n",
      "incremental @ file:///tmp/build/80754af9/incremental_1636629750599/work\r\n",
      "inflection==0.5.1\r\n",
      "iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work\r\n",
      "intake @ file:///opt/conda/conda-bld/intake_1647436631684/work\r\n",
      "intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work\r\n",
      "iopath==0.1.10\r\n",
      "ipykernel @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_05yte6zd0k/croots/recipe/ipykernel_1662361808878/work\r\n",
      "ipython @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b9echyik_d/croots/recipe/ipython_1659529861316/work\r\n",
      "ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work\r\n",
      "ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work\r\n",
      "isort @ file:///tmp/build/80754af9/isort_1628603791788/work\r\n",
      "itemadapter @ file:///tmp/build/80754af9/itemadapter_1626442940632/work\r\n",
      "itemloaders @ file:///opt/conda/conda-bld/itemloaders_1646805235997/work\r\n",
      "itsdangerous @ file:///tmp/build/80754af9/itsdangerous_1621432558163/work\r\n",
      "jdcal @ file:///Users/ktietz/demo/mc3/conda-bld/jdcal_1630584345063/work\r\n",
      "jedi @ file:///opt/concourse/worker/volumes/live/89be3eb0-a85c-453b-67dd-f706f2fa4c43/volume/jedi_1644315269953/work\r\n",
      "jellyfish @ file:///opt/concourse/worker/volumes/live/a3ea5aa0-13fc-40da-68a6-cbc194ed3c8f/volume/jellyfish_1647962585030/work\r\n",
      "Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work\r\n",
      "jinja2-time @ file:///opt/conda/conda-bld/jinja2-time_1649251842261/work\r\n",
      "jmespath @ file:///Users/ktietz/demo/mc3/conda-bld/jmespath_1630583964805/work\r\n",
      "joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work\r\n",
      "json5 @ file:///tmp/build/80754af9/json5_1624432770122/work\r\n",
      "jsonschema @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_d832da7jx3/croots/recipe/jsonschema_1663375475386/work\r\n",
      "jupyter @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e35x81mm4c/croots/recipe/jupyter_1659349054503/work\r\n",
      "jupyter-console @ file:///opt/conda/conda-bld/jupyter_console_1647002188872/work\r\n",
      "jupyter-server @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_dd29643e-0dc7-4523-9371-1e357e0016ceqm1g9hiw/croots/recipe/jupyter_server_1658754492837/work\r\n",
      "jupyter_client @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_41tzpfqkok/croots/recipe/jupyter_client_1661848920196/work\r\n",
      "jupyter_core @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_f5x3brmrnq/croots/recipe/jupyter_core_1664917315750/work\r\n",
      "jupyterlab @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_2af04qzhn_/croots/recipe/jupyterlab_1658907539952/work\r\n",
      "jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work\r\n",
      "jupyterlab-server @ file:///opt/conda/conda-bld/jupyterlab_server_1644500396812/work\r\n",
      "jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work\r\n",
      "keras==2.11.0\r\n",
      "keyring @ file:///opt/concourse/worker/volumes/live/33b3e085-74e6-4f7b-77a0-470eb43e69ae/volume/keyring_1638531366470/work\r\n",
      "kiwisolver @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_ca2945cc-8f2f-407b-8e24-f05d29ee2f4fvto5sdlk/croots/recipe/kiwisolver_1653292053344/work\r\n",
      "kraken==4.3.5\r\n",
      "langcodes==3.3.0\r\n",
      "layoutparser==0.3.4\r\n",
      "lazy-object-proxy @ file:///opt/concourse/worker/volumes/live/a169db40-97bf-4f51-6893-dc751f705b7b/volume/lazy-object-proxy_1616529067444/work\r\n",
      "libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work\r\n",
      "libclang==14.0.6\r\n",
      "lightning-utilities==0.7.1\r\n",
      "llvmlite==0.38.0\r\n",
      "locket @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_81b4c56b-0395-495d-81c1-83208d36944d357hqdd0/croots/recipe/locket_1652903116052/work\r\n",
      "lxml @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1902c961-4bd2-4871-a3c5-70b7317a6521kpj7nz2o/croots/recipe/lxml_1657545138937/work\r\n",
      "lz4 @ file:///opt/concourse/worker/volumes/live/5cb15f71-8949-4447-4576-dc636f8e7723/volume/lz4_1619516482660/work\r\n",
      "mapclassify==2.4.3\r\n",
      "Markdown @ file:///opt/concourse/worker/volumes/live/022ad249-0648-42f1-5668-a0ceb0c8ad95/volume/markdown_1614363814264/work\r\n",
      "markdown-it-py==2.2.0\r\n",
      "MarkupSafe @ file:///opt/concourse/worker/volumes/live/1bcf0940-5bf8-4171-61e3-2133f5885e8b/volume/markupsafe_1621528148241/work\r\n",
      "matplotlib @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_757ijfo2tl/croots/recipe/matplotlib-suite_1660167932741/work\r\n",
      "matplotlib-inline @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9ddl71oqte/croots/recipe/matplotlib-inline_1662014471815/work\r\n",
      "mccabe @ file:///opt/conda/conda-bld/mccabe_1644221741721/work\r\n",
      "mdurl==0.1.2\r\n",
      "mean-average-precision==2021.4.26.0\r\n",
      "mistune @ file:///opt/concourse/worker/volumes/live/4217afd5-dad1-438d-6f79-e4992ccda0e5/volume/mistune_1607364880245/work\r\n",
      "mkl-fft==1.3.1\r\n",
      "mkl-random @ file:///opt/concourse/worker/volumes/live/0cda23d8-7460-44b2-7e5d-3c76a8a0ca7e/volume/mkl_random_1626186083266/work\r\n",
      "mkl-service==2.4.0\r\n",
      "mock @ file:///tmp/build/80754af9/mock_1607622725907/work\r\n",
      "mpmath==1.2.1\r\n",
      "msgpack @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_8471ad7f-dce1-4146-86d4-c2864258a94duzpja450/croots/recipe/msgpack-python_1652362671722/work\r\n",
      "multidict==6.0.4\r\n",
      "multipledispatch @ file:///opt/concourse/worker/volumes/live/ae29ad0f-3a64-4ff5-7393-0aa95f2c9f85/volume/multipledispatch_1607574242710/work\r\n",
      "munch==2.5.0\r\n",
      "munkres==1.1.4\r\n",
      "murmurhash==1.0.9\r\n",
      "mypy-extensions==0.4.3\r\n",
      "navigator-updater==0.3.0\r\n",
      "nbclassic @ file:///opt/conda/conda-bld/nbclassic_1644943264176/work\r\n",
      "nbclient @ file:///opt/concourse/worker/volumes/live/fcea0efc-2a08-48fd-5c55-85ef78e0ea28/volume/nbclient_1650308406463/work\r\n",
      "nbconvert @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_croot-mv2swkk7/nbconvert_1649751922903/work\r\n",
      "nbformat @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cdvzwfxs_z/croots/recipe/nbformat_1663744956173/work\r\n",
      "nest-asyncio @ file:///opt/concourse/worker/volumes/live/ddf592a1-304c-41a6-6d59-2d4687652b8f/volume/nest-asyncio_1649847942674/work\r\n",
      "networkx @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_6afc8f17-1d67-4285-b2c6-55302f6d1d829k5owdkh/croots/recipe/networkx_1657784106447/work\r\n",
      "nltk @ file:///opt/conda/conda-bld/nltk_1645628263994/work\r\n",
      "nose @ file:///opt/conda/conda-bld/nose_1642704612149/work\r\n",
      "notebook @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_98mevid06x/croots/recipe/notebook_1659083668559/work\r\n",
      "numba @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_croot-p56zvl1f/numba_1648040520212/work\r\n",
      "numexpr @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_f4cadb13-5662-4009-98e5-0105539d6a65fifix2d5/croots/recipe/numexpr_1656940304949/work\r\n",
      "numpy==1.23.5\r\n",
      "numpydoc @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_753dae38-7ca3-4e28-bd02-7f92dc5dac540wd4kft3/croots/recipe/numpydoc_1657529877062/work\r\n",
      "oauthlib==3.2.2\r\n",
      "olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work\r\n",
      "omegaconf==2.3.0\r\n",
      "opencv-python==4.7.0.68\r\n",
      "openpyxl==3.0.10\r\n",
      "opt-einsum==3.3.0\r\n",
      "packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work\r\n",
      "pandas==1.4.4\r\n",
      "pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work\r\n",
      "panel @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_41dde6ca-7b2c-48c7-bc25-73a832237d768xjx_7ml/croots/recipe/panel_1658133829944/work\r\n",
      "param @ file:///tmp/build/80754af9/param_1636647414893/work\r\n",
      "parsel @ file:///opt/concourse/worker/volumes/live/82c6082c-054e-4c34-7398-3c26404de88b/volume/parsel_1646739973951/work\r\n",
      "parso @ file:///opt/conda/conda-bld/parso_1641458642106/work\r\n",
      "partd @ file:///opt/conda/conda-bld/partd_1647245470509/work\r\n",
      "pathlib @ file:///Users/ktietz/demo/mc3/conda-bld/pathlib_1629713961906/work\r\n",
      "pathspec @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e2t1r2kdq7/croots/recipe/pathspec_1659627124303/work\r\n",
      "pathy==0.10.1\r\n",
      "patsy==0.5.2\r\n",
      "pdf2image==1.16.2\r\n",
      "pdfminer.six==20221105\r\n",
      "pdfplumber==0.8.0\r\n",
      "pep8==1.7.1\r\n",
      "perdido==0.1.31\r\n",
      "pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work\r\n",
      "pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work\r\n",
      "Pillow==9.2.0\r\n",
      "pkginfo @ file:///tmp/build/80754af9/pkginfo_1643162084911/work\r\n",
      "plac==1.1.3\r\n",
      "platformdirs @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7fs8_2xgrm/croots/recipe/platformdirs_1662711383474/work\r\n",
      "plotly @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b7601a7c-071f-4424-ad46-f00f32c1766ccwgx0ywh/croots/recipe/plotly_1658160061089/work\r\n",
      "pluggy @ file:///opt/concourse/worker/volumes/live/42ef51ae-f79c-40e0-6d26-eb6fe9d8ba6e/volume/pluggy_1648042596777/work\r\n",
      "ply==3.11\r\n",
      "portalocker==2.7.0\r\n",
      "poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work\r\n",
      "preshed==3.0.8\r\n",
      "prometheus-client @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_19kjbndib7/croots/recipe/prometheus_client_1659455105394/work\r\n",
      "prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work\r\n",
      "Protego @ file:///tmp/build/80754af9/protego_1598657180827/work\r\n",
      "protobuf==3.19.6\r\n",
      "psutil @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_c9b604bf-685f-47f6-8304-238e4e70557e1o7mmsot/croots/recipe/psutil_1656431274701/work\r\n",
      "ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl\r\n",
      "py @ file:///opt/conda/conda-bld/py_1644396412707/work\r\n",
      "pyarrow==11.0.0\r\n",
      "pyasn1 @ file:///Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/work\r\n",
      "pyasn1-modules==0.2.8\r\n",
      "pycocotools==2.0.6\r\n",
      "pycodestyle @ file:///tmp/build/80754af9/pycodestyle_1636635402688/work\r\n",
      "pycosat==0.6.3\r\n",
      "pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work\r\n",
      "pyct @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_615564ea-cf79-46b0-83e7-0a37ab5db74a2ay4a5f0/croots/recipe/pyct_1658500312593/work\r\n",
      "pycurl==7.45.1\r\n",
      "pydantic==1.10.2\r\n",
      "PyDispatcher==2.0.5\r\n",
      "pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work\r\n",
      "pydot==1.4.2\r\n",
      "pyerfa @ file:///opt/concourse/worker/volumes/live/fef1f482-1dec-42b9-4439-b8031d24ea69/volume/pyerfa_1621560786048/work\r\n",
      "pyflakes @ file:///tmp/build/80754af9/pyflakes_1636644436481/work\r\n",
      "Pygments==2.14.0\r\n",
      "PyHamcrest @ file:///tmp/build/80754af9/pyhamcrest_1615748656804/work\r\n",
      "PyJWT @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_eec47dd9-fcc8-4e06-bbca-6138d11dbbcch6zasfc4/croots/recipe/pyjwt_1657544589510/work\r\n",
      "pylint @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e75_4ydew9/croots/recipe/pylint_1659110352634/work\r\n",
      "pyls-spyder==0.4.0\r\n",
      "pynsee==0.1.1\r\n",
      "pyobjc-core @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_e7giy3a869/croots/recipe/pyobjc-core_1661848172499/work\r\n",
      "pyobjc-framework-Cocoa @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4c2umern3y/croots/recipe/pyobjc-framework-cocoa_1661850714385/work\r\n",
      "pyobjc-framework-CoreServices @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4717m_ngol/croots/recipe/pyobjc-framework-coreservices_1661853392396/work\r\n",
      "pyobjc-framework-FSEvents @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5atkr691rb/croots/recipe/pyobjc-framework-fsevents_1661852390555/work\r\n",
      "pyodbc @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_18mhb222la/croots/recipe/pyodbc_1659513803477/work\r\n",
      "pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work\r\n",
      "pyparsing==2.4.7\r\n",
      "pyproj==3.4.0\r\n",
      "PyQt5-sip==12.11.0\r\n",
      "pyrsistent @ file:///opt/concourse/worker/volumes/live/76cffa60-bd33-4155-4e83-ea03c38b1294/volume/pyrsistent_1636111020441/work\r\n",
      "PySocks @ file:///opt/concourse/worker/volumes/live/112288ac-9cb0-4e73-768b-13baf4ca6419/volume/pysocks_1605305820043/work\r\n",
      "pytest==7.1.2\r\n",
      "python-bidi==0.4.2\r\n",
      "python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work\r\n",
      "python-dotenv==0.21.1\r\n",
      "python-lsp-black @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_14xl6hg757/croots/recipe/python-lsp-black_1661852036282/work\r\n",
      "python-lsp-jsonrpc==1.0.0\r\n",
      "python-lsp-server @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_6cu9im5n5w/croots/recipe/python-lsp-server_1661813818984/work\r\n",
      "python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work\r\n",
      "python-snappy @ file:///opt/concourse/worker/volumes/live/8c331f10-f7c9-4f6b-5744-375e3450cc0a/volume/python-snappy_1610133354807/work\r\n",
      "pytorch-lightning==1.9.3\r\n",
      "pytz @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1caf090c-01b6-4973-adac-d2eb884a674e7zonb9eb/croots/recipe/pytz_1654762641285/work\r\n",
      "pyviz-comms @ file:///tmp/build/80754af9/pyviz_comms_1623747165329/work\r\n",
      "PyWavelets @ file:///opt/concourse/worker/volumes/live/6f70ac9d-9e9e-4250-6d7d-22d19aef341f/volume/pywavelets_1648727880440/work\r\n",
      "PyYAML==6.0\r\n",
      "pyzmq @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_15f7a459-ad98-422b-b8da-cbf1f626e2115nt0ocwy/croots/recipe/pyzmq_1657724193704/work\r\n",
      "QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work\r\n",
      "qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl\r\n",
      "QtAwesome @ file:///tmp/build/80754af9/qtawesome_1637160816833/work\r\n",
      "qtconsole @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_552cqm7spz/croots/recipe/qtconsole_1662018258355/work\r\n",
      "QtPy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_4e5ppuhz0f/croots/recipe/qtpy_1662014536017/work\r\n",
      "queuelib==1.5.0\r\n",
      "regex @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_978efa21-43f5-4f43-9f25-acd8393817ddce2xcjaf/croots/recipe/regex_1658257186496/work\r\n",
      "requests @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_516b78ce-034d-4395-b9b5-1d78c2847384qtnol99l/croots/recipe/requests_1657734628886/work\r\n",
      "requests-file @ file:///Users/ktietz/demo/mc3/conda-bld/requests-file_1629455781986/work\r\n",
      "requests-oauthlib==1.3.1\r\n",
      "requests-toolbelt==0.10.1\r\n",
      "rich==13.3.1\r\n",
      "roboflow==0.2.31\r\n",
      "rope @ file:///opt/conda/conda-bld/rope_1643788605236/work\r\n",
      "rsa==4.9\r\n",
      "Rtree @ file:///opt/concourse/worker/volumes/live/18283f9b-719e-45b1-7f3a-937f49358be4/volume/rtree_1618420836397/work\r\n",
      "ruamel-yaml-conda @ file:///opt/concourse/worker/volumes/live/e81cf0fe-611a-498e-6e69-a7320057c1ac/volume/ruamel_yaml_1616016689696/work\r\n",
      "ruamel.yaml @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7de1zqcaou/croot/ruamel.yaml_1666304553877/work\r\n",
      "ruamel.yaml.clib @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_c7s0zxy4t2/croot/ruamel.yaml.clib_1666302244557/work\r\n",
      "s3transfer @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_07692347-3b2f-44eb-9a12-5e0d23d67c1b9oqlb6o4/croots/recipe/s3transfer_1654524216219/work\r\n",
      "scikit-image @ file:///opt/concourse/worker/volumes/live/584d0455-dcb7-4cf1-5977-c077944180ee/volume/scikit-image_1648214186784/work\r\n",
      "scikit-learn @ file:///opt/concourse/worker/volumes/live/cffa5efe-beec-4a37-5774-350794e43990/volume/scikit-learn_1642617139916/work\r\n",
      "scikit-learn-intelex==2021.20221004.121333\r\n",
      "scipy==1.9.1\r\n",
      "Scrapy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_76af7rt3wk/croots/recipe/scrapy_1659598702735/work\r\n",
      "seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work\r\n",
      "Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work\r\n",
      "service-identity @ file:///Users/ktietz/demo/mc3/conda-bld/service_identity_1629460757137/work\r\n",
      "Shapely==1.8.5\r\n",
      "shapley==1.0.3\r\n",
      "sip @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_88z1zrsfrf/croots/recipe/sip_1659012373083/work\r\n",
      "six @ file:///tmp/build/80754af9/six_1644875935023/work\r\n",
      "sklearn==0.0.post1\r\n",
      "smart-open @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_27148096-9ddc-448c-830e-fb4829d46f5dwl2am402/croots/recipe/smart_open_1651563554983/work\r\n",
      "smmap==5.0.0\r\n",
      "sniffio @ file:///opt/concourse/worker/volumes/live/38ca9e9e-09d1-4d43-5a0f-b546422e7807/volume/sniffio_1614030472707/work\r\n",
      "snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1637937080595/work\r\n",
      "sortedcollections @ file:///tmp/build/80754af9/sortedcollections_1611172717284/work\r\n",
      "sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work\r\n",
      "soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work\r\n",
      "spacy==2.3.9\r\n",
      "spacy-legacy==3.0.10\r\n",
      "spacy-loggers==1.0.4\r\n",
      "Sphinx @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5d9f8d69-b80c-4ca1-8876-1698c70b1faeqe461tx8/croots/recipe/sphinx_1657784127805/work\r\n",
      "sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work\r\n",
      "sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work\r\n",
      "sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work\r\n",
      "sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work\r\n",
      "sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work\r\n",
      "sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work\r\n",
      "spyder @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_97gv8v17po/croots/recipe/spyder_1663056808858/work\r\n",
      "spyder-kernels @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1c7pyd81si/croots/recipe/spyder-kernels_1662457889999/work\r\n",
      "SQLAlchemy @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_47054e44-1f88-4a8b-9ca4-67b36ce38181xyx8z2m5/croots/recipe/sqlalchemy_1657867866169/work\r\n",
      "srsly==1.0.6\r\n",
      "stanza==1.4.2\r\n",
      "statsmodels @ file:///opt/concourse/worker/volumes/live/90a089a9-fdd6-4c7e-631b-5fdf9cf55d62/volume/statsmodels_1648033311105/work\r\n",
      "sympy @ file:///opt/concourse/worker/volumes/live/2af8c70b-e999-41ad-6ca8-39318707cbda/volume/sympy_1647854069899/work\r\n",
      "tables @ file:///opt/concourse/worker/volumes/live/daa73f70-754b-4f28-73ce-6f96c40f4b9d/volume/pytables_1607975400838/work\r\n",
      "tabulate @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_a6553360-8167-4574-96ae-f76ab756a64bn2vcri8q/croots/recipe/tabulate_1657784111302/work\r\n",
      "TBB==0.2\r\n",
      "tblib @ file:///Users/ktietz/demo/mc3/conda-bld/tblib_1629402031467/work\r\n",
      "tenacity @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_15d3bbab-3059-4048-adcb-986fb2669dd5nujdx5qd/croots/recipe/tenacity_1657899116644/work\r\n",
      "tensorboard==2.11.0\r\n",
      "tensorboard-data-server==0.6.1\r\n",
      "tensorboard-plugin-wit==1.8.1\r\n",
      "tensorflow==2.11.0\r\n",
      "tensorflow-estimator==2.11.0\r\n",
      "tensorflow-io-gcs-filesystem==0.28.0\r\n",
      "termcolor==2.1.1\r\n",
      "terminado @ file:///opt/concourse/worker/volumes/live/1e61dc32-e381-4730-4e5e-6cfec5c3c4a5/volume/terminado_1644322614203/work\r\n",
      "testpath @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_aaf4aec7-dbb6-43d6-9707-824338b4efc82yrt6xjp/croots/recipe/testpath_1655908558843/work\r\n",
      "text-unidecode @ file:///Users/ktietz/demo/mc3/conda-bld/text-unidecode_1629401354553/work\r\n",
      "textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work\r\n",
      "texthero==1.1.0\r\n",
      "thinc==7.4.6\r\n",
      "thop==0.1.1.post2209072238\r\n",
      "threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work\r\n",
      "three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work\r\n",
      "tifffile @ file:///tmp/build/80754af9/tifffile_1627275862826/work\r\n",
      "tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work\r\n",
      "tldextract @ file:///opt/conda/conda-bld/tldextract_1646638314385/work\r\n",
      "tokenizers==0.13.2\r\n",
      "toml @ file:///tmp/build/80754af9/toml_1616166611790/work\r\n",
      "tomli @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_90762ba4-f339-47e8-bd29-416854a59b233d27hku_/croots/recipe/tomli_1657175507767/work\r\n",
      "tomlkit @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_5fgtm9if1m/croots/recipe/tomlkit_1658946891645/work\r\n",
      "toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work\r\n",
      "torch==1.13.1\r\n",
      "torchaudio==0.13.1\r\n",
      "torchmetrics==0.11.1\r\n",
      "torchvision==0.14.1\r\n",
      "tornado @ file:///opt/concourse/worker/volumes/live/2c1a63a2-006b-48ee-56b9-0cfe8b4927f9/volume/tornado_1606942321278/work\r\n",
      "tqdm @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_2adqcbsqqd/croots/recipe/tqdm_1664392689227/work\r\n",
      "traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work\r\n",
      "transformers==4.25.1\r\n",
      "Twisted @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_daykstm3mh/croots/recipe/twisted_1659592770155/work\r\n",
      "typer==0.7.0\r\n",
      "typing_extensions @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_ff5_5nqr6l/croots/recipe/typing_extensions_1659638832447/work\r\n",
      "ujson @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_cf44fbd5-5db0-48cf-86c4-c8d4e74d1cbbwhgckc99/croots/recipe/ujson_1657544919410/work\r\n",
      "Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work\r\n",
      "urllib3 @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_53dwuk2xkk/croots/recipe/urllib3_1659110467968/work\r\n",
      "w3lib @ file:///Users/ktietz/demo/mc3/conda-bld/w3lib_1629359764703/work\r\n",
      "Wand==0.6.11\r\n",
      "wasabi==0.10.1\r\n",
      "watchdog @ file:///opt/concourse/worker/volumes/live/bc34f9ce-893b-443f-56fb-9256c33ecf2a/volume/watchdog_1638367303330/work\r\n",
      "wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work\r\n",
      "webencodings==0.5.1\r\n",
      "websocket-client @ file:///opt/concourse/worker/volumes/live/5baed9cd-40fb-4fbe-6721-9568cdd0f2d7/volume/websocket-client_1614804245073/work\r\n",
      "Werkzeug @ file:///opt/conda/conda-bld/werkzeug_1645628268370/work\r\n",
      "wget==3.2\r\n",
      "whatthepatch @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0aabmq0ph3/croots/recipe/whatthepatch_1661795995892/work\r\n",
      "widgetsnbextension @ file:///opt/concourse/worker/volumes/live/8bad7157-f9ed-4ea5-5a30-5ca326558415/volume/widgetsnbextension_1645009368149/work\r\n",
      "wordcloud==1.8.2.2\r\n",
      "wrapt @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_1ade1f68-8354-4db8-830b-ff3072015779vd_2hm7k/croots/recipe/wrapt_1657814407132/work\r\n",
      "wurlitzer @ file:///opt/concourse/worker/volumes/live/a2b1dfd8-5830-41c1-6a08-9a84d13fec28/volume/wurlitzer_1638368180115/work\r\n",
      "xarray @ file:///opt/conda/conda-bld/xarray_1639166117697/work\r\n",
      "xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work\r\n",
      "XlsxWriter @ file:///opt/conda/conda-bld/xlsxwriter_1649073856329/work\r\n",
      "xlwings @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_05prpwd36w/croots/recipe/xlwings_1664932816578/work\r\n",
      "yacs==0.1.8\r\n",
      "YALTAi==0.1.1\r\n",
      "yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work\r\n",
      "yarl==1.8.2\r\n",
      "zict==2.1.0\r\n",
      "zipp @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_b279673d-f037-44c7-8773-c5a6b6f51037d3wfr9cq/croots/recipe/zipp_1652341773612/work\r\n",
      "zope.interface @ file:///opt/concourse/worker/volumes/live/8c2d4bd1-6406-47f0-45ce-890992bafbf6/volume/zope.interface_1625036159007/work\r\n"
     ]
    }
   ],
   "source": [
    "! pip freeze"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e04c718",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
